cls
cls
cls
echo .
echo jhk jennidy gobo
pause
cls
echo off "BBB_BB______BBB___BBB_______________________B__________________B____________________BBB____BBBBBBBBBB_"
echo off "BB____B_______B________________________________B_____________B_B__________B__________B___BBBBBBBBBBBBB"
echo off "__B_B_B_____B____BBBB_____BB______BB_______________B_88_________B__________________BBBBBBBBBBBBBBB___B"
echo off "BBBB________BBB_BB______BB__________BBB______________88____________8________________BBBBBBBBBBBBBBBBB_"
echo off "_BBBBB____________B_______________________BB_88&&WWMWW&&8________B________________BB_____BBBB__BBBBBB_"
echo off "____BBB_B_B__B_____B_________B________8&WMoahbdqmmmwwqpbka#W8___B_____________B____B__B__BBBBBBBB_BBB_"
echo off "___BBB__B__8________B______________&MokdpwZ00QLCCLUJLQCJL0ZwdbaM&8____BBBB_________________B__B_____BB"
echo off "___________B_______________B___8W*admOm0CUUUYYYUYXUzcYYYzXYYUQ0ZwpkoM&__BB___________B_____B__B_____BB"
echo off "BBBBB_____B____BB__BB_____B_&W#dwm0QLCUUYzczJ0JJ0OZOLCLJJUYYzzUJ0QLOwdba*W8_B____B_________BB______BBB"
echo off "_BB8____B_____B_____8___B_&*pphZUXzzzzXXczYCmwwZwpqZLCCCQ0QCYXUJJJUUJLQOmpkoW8_B_8__________B_______BB"
echo off "BB___B____________B_8__8#kwQJcuJUYJ0QUUYzvczCqq0OOZQXXXzUCQZZmZQCQZJYUJUJQOwpk#&88_____8_________B____"
echo off "___BBB______B___8B__B8oqQUYzzYuxCZZQLzuuuvvcXZpLJLLUcvvvuucYUCQmZ0mqZ0Q0QJUQ0qakhW____________________"
echo off "_B_______________B8MhmLYzczYQOwwQ0OJvrrrjt/fxzLJcvJztfrrrfjuuuczJL0mppwm0w0XzY0mwb#_B__BB_______B_____"
echo off "_B____B__________MhmCUYXXC0qbpwZZ0Uv/}[}}[[}(jnXct/t[]{11(tfftfffjvLLU0qwLLZwmmZOpdo&_________________"
echo off "_____8_88___BB_WkQUUQqqZmpdqZCYcjff(]ili||i<-[|zU/+-<l<++~+?[}}[{tnfjXcnXCLOmmwqmZqdk#_B______BB______"
echo off "_____8__8_____#pOJJJXvcYZZLUzrt(1]+<<i>|i<ilIl?xY/+--~~++~ll><~_]]}1|/1)/rvXULwpwwZmdk#_B_____________"
echo off "________8___8*pOQJJOpkhqQznr/1}]__>i<<~~<++++><)v/~-+<+++_+<>|lIIl-}[}[}(fjrncY0mmmZZdhM_____BBB__BB__"
echo off "___B_8__8_B_*pOCYJmbkqLYvj|[_-_+<i>><>ii>>>>><>]x)<++++<~_]]--???_+~_-?_?11}(txvJ0ZmZmphM_BB_8________"
echo off "_________B_MbZQCQqbp0QJn(]+<~~~<><<~+<>ii>>><<i_f{i+-<>ii>~~~+<i><~~+-+i<-?[(||jvC0Ommmph&B__________B"
echo off "__88___8__8awOQZwbdZJcXQv[l;|<<>i|l;;i<-+i<<~+|>|}|+-+i|||||>i|i>i<+__i:;>+?{{{txzQ0Zwwwd*8__________B"
echo off "__________MdwZOZwdOJv(?)t([~>|i>>i|i+__+~><<~+>I[(:,~--->lI|li+--_+<>i><<>i<-]1|fuYQZZ0mphW____B_____B"
echo off "_________WhmC0mpkwJx1}[~|>+--+i><>+_<<<~~~+++>|:+(l|??_<i<+_?-+_?]]]?-++<<i|<_]1|rzCOZZ0Zb#8_____B____"
echo off "_8_____B_#dmL0pmOYr|(]<I;i~~~+_+~>~_><-?-+~~l*^^>f]_-<~~_?-_++-_><~+~>>~_+i>_?}(fxvYL000Zqo&__________"
echo off "_8_______#qQOmZwmQn(1-<l;|++<<~iI|~_>i>~_???][]>:})_-++____++>>~~++~~<~__><+_?]1/rvYC0OQQmkM__________"
echo off "88_8____8omLQZZ00Uxt1-<I:I+_<<<+__+++~|llll:I>+]+|++_?-~ii|><+_+_+~+++_-il+__]}1/rzJ0Z0QQ0dM8_B_______"
echo off "___88___8omLLOpkwQc|{]~|;l+?+i>>><++__<>>i||li_]-i+_>-?-??~+_+___~><~_->l>+-?]{|fuJZpm0JYQd#8_________"
echo off "____8___8*qCJ0mbpmJr([+|;;|<~~<>>>>>>i<+~<++<~>_[>+>:_?[?+<__+<ii>+??~~+<+_?[}(fnUZqZCJUUQdM88____8__B"
echo off "____8__B_#dQLQmwww0z/[]_<;,:;>+_~<i>>i><>>~<>>><]_[-I+_~>>~+_~>>~-?_<>++-][}1|jnzQpddmQXY0d#8_________"
echo off "_______B_&kOJJOwZZmZCvf1-+i;*^I+?_~<ii|iilil;l|+?i_[>~++__+~~~_-?_<<~~+-?})|fnYmkpdahZCJUQd#8B_B______"
echo off "8___88__B8*wCJUQQw##kmCvrft(?i,,i_?+i|||iiil;I|+?<+{<+-<i|i>--_]-<<<~-][)fuUZb#odhoobOJzYQp*&8_BBBB___"
echo off "____888__8MkQYCLQwh#MohqCcr|}]-+~--__--?]??-_>|>]?i]{__iIl+--]-<><_][)/rzQd#*hpdoahkhdOJYUmhW8________"
echo off "__8__8____&awJYJQQ0dMMbbhpZJcx/1?<>>iII;:l<+-_ii~]~-t}+<<<~<_-+_-}1(jcLqhhbbqmmwwOQLLQQ0ZZZp*8________"
echo off "____8_____8#dLczJ0mZmZZhWM#abpmCvf)-~ilI;|<+<<~~~-+-r1-?---?[[}}/uY0qkmQQJYUCQQLQLJLQ0LLCJUQq#8_______"
echo off "__________8#bOYcUZwdpmbkpwqb*#oohd0Xr|1->lli<~_+~]<?Uv?>+[{}]}/xXOpZCJLJvczYJUUQ0000QLJLQQCCLm#_B__8__"
echo off "___8______8owUvCphpmZmZwdqOQLCLQOwpkqLXx/}_>|;;,;<+fLJt_?})|juYObhpZZUrnXL0OZO0ZwOLJUCQ00ZwZwwdM______"
echo off "_____88__BWbLYZq0JL0OOwOJJQQQQ0UJm0OdkkpQzf)}_<|>1/uYQLznxxuzJmahqOLntcLCYurffjxcUQ0JvjnXLZwmqba8___B_"
echo off "____8__BB_oOUJQZ000UYCQ0mqddpqwmZOUXCOZqaamYn/txuzXcuzOdddqmZZhwUQJzcYXn|[-+~~~_[)tvLZCvxxYZqbba8B__8_"
echo off "___88__BBWpYzZqZ0QQ0Q0ZwmLXvnrxuvY0wmw0XzJdp00wmQZQn(fJZUYJ0OObmZbmmZz/[_<l:,**:Ii_{fXOZCUXLmmpo&_B___"
echo off "_____B_BB*QUmdqpmYcuzLQYnj|}?__[1(fuLmZwwmdqO0OLXUYct/cLQU0dqphq0ZmpLr1_i,*;i><|;,;~}fYmwZZ0mpb*8_____"
echo off "__88__B__a0mbdwZcjnYOQXx}i;;ll;,:i[/xUqpZwdoabdpt(J(_+<ULtOhhoakpwdpJj{>,;+fXJUt+I:l-(uZqwqdpbhM__8___"
echo off "______B_8aqpbddQnuCZwJu}I:+tXUc|>:>}|u0dpQmM#dbpJYbqnvOMdXmhpwdhppkbLx1i:i(JphqY(i:l-|vZbpqpba*MW8____"
echo off "___88____#bdbbk0LZqp0zf+,I)CbapU};;-(rJdhkkadZwqJfrwqJmkUzmZObdhMhhowzt?I|]xJLX(>,I+1jUpo#W&WW888_____"
echo off "_____B___8obbbbbhbppOzj-:;[cZwQr~,I]/nCdaoMoqpXYOv|jCQznun0wUZbwbooWoZXf]>li<<i;,I-|rYwkkpqbhho8B_____"
echo off "_____8____WhdkdbhbppwJu/+;,|_]+I*|[(tcO*WoMdmdvzmzuu/ncjvzcmCvwdwpwwbhpQct{_~<<_}tnvJmdqZwpqqpd#_B8___"
echo off "___8__B__8&M#*MW###*odLcx(->lIl>?(trzmaodpbOdZtcQJU/1rf/[[JZXxnwapwZOqdbdmLYzczzYUCZZLJ0mqdqmZma&_____"
echo off "_BBB_______888hpddbdpbdOJXcnrrrxnvzLwkbm0mmddYXfxpJ)-)f({tOaJtXUOpkpOOOmwqppdddhbZLQ0mqwwdbmQLZhM8____"
echo off "_____________WpZwpppqZ0mwmOQLCJQOmpdqm0JCZqwOJOCmWbvvzxrtvhWoYLZC0mqdpZZpppwOmwO0OmqwmwqpbpOUYZb#8____"
echo off "__B____888___Mp0wddqOZ0QLLLQZwwOL0OwwCYQpbwmZQ0YckWoWkYcnL#MmxcqqO00O0LL0QmpwwwmwmZZZmqwmmJnxzmk#_____"
echo off "_____88____8_MbQJOpbqOOwwmZZLYU0wpw0UYQZwOCQOm0r)/ZMkxrUU0MkvrvQwmQJ0OJUUUzzzvrrvUL0ZZQQYxuvcUwhW____8"
echo off "_______B_____WhmJcLpbbqwZ0QQLJCcvXYzcYUJ0OQC0pd0X|v*&bQCL0aaCOzzdZ0LCQO00YnnYCJuxcXUcuxnnffncLpa8B____"
echo off "_____________&obZYnnCZpdmmOLYrjXCUJUJYY0ZOQLLLmb0YwMWOZ0n0YXhpbdZmQJCOqwQ0OC0YxccJLzczvnxxjuzOb*8B___8"
echo off "__________BB8_MhpLXntjvUUUYUQZm0YLZUXLOZmZLUJUXQbMhaMwZbwpbb*ohdpZUUQLQOwqLXUXnnYLQ0Qcnx|/jcCmkW__B___"
echo off "_________88___8obmJvnxfxvuXQOQc)[nJzUOqOvfnQOOmJjfuUmdwa*kZcf/|/cQm0t--?(Cp0zntjLCJJXUcrrrrnJwo8B_____"
echo off "_______8_88____&ad0UvrnxjvXvvvYzrzuvOdJ{<>>]nr){[]_?1nw*awz|??[{)|vc[|;;>|md0Y)tzLLYJJvfrxxcLq#8_____8"
echo off "__B__88_88____BBWkwQYnxnrjfcJzxfjrvLpqr+ll>[cc//txt1)nZkawzt)jznxfxJzf(|xvZwCv|tnvUJYjfurrfz0pM_______"
echo off "___B______8888888Mbp0Yn//|ncXJXujrxcZdYxrfxxvXcXLC(-++/mhJ[<~-nOOJUYcuzzjUm0JcznrXXcvvjxntrz0dW_______"
echo off "___________88_B___#qwZzjtfrxvcnxx//nJOmu(fjffjczuvr]+_jmdZf]-1ur(()t/])Um0CJrrvruvXJUzu)|r/XZk&88_____"
echo off "______B_888__888__8apmLf|f|nzYUzxjffcJQqpQr)vc}?n0YXCOmCzQm0JUOwctzpwLqhqZZJfuzrxXYULn|tt/nJZa8_______"
echo off "___________8888_____WbLrt(/jcQLznvrfvCZmZpkdbhp0qokdqh*d0wMobk**dpookbwO0OLjtxruuxzUnttjj|rQwo________"
echo off "__B___________8888BBMwJx|/(1/zLXvvnt1xOmmZOZZd*#a#&#a#WW*#WWMMWM*M*wLLQ0ZLrtunttjnr/fjj///v0pM________"
echo off "B_____B_______8_____&bOzjttt(xvrrrxxf|vOZQUY0kW&&8__8__8_88____BB_8hdbm0ctuvrjxt|rnnx/(t/fYZb&___B____"
echo off "B____________88_8___8owUf/(/tfvn(fxrzzrrCwwbka8_____8_8_8_88888__&adhqpOYzn/(|trxxr/ffft|xQwo_________"
echo off "_8___________________MwQct//tnnXzr|})|xXQOwbkba&&88888__B_8___88_oqhhdq0Lzj|rnxxrxrxftjtfYZdW_B_______"
echo off "B_B_________BB_____8_&kOn/fjxjxnzYxrjjvJLZdkhdZd#M##MW&&&88&WWMWMppkbdwdbZZZcrnnnrftj/|rvLwa__________"
echo off "_______________8888___*mYxjjjjfruCXf/zZLQmpbkdZCZooo*o*MM##*o*#hLLpbbdphmUXC0zxcvrxrxjrrXZb8B__8______"
echo off "______B______8_______B&b0vjfjjjruCLQO0OpkpwqddmQLCpokdkkkahhkhqJJLQZwqqdbwOddUzcnurrffxz0dW___________"
echo off "_____B_______8__8____8_#pJnxrrffruXJwhakqZZmpqm00mwddZmwqppqOUncJLOOmmZwbkhaLzvfxxxnxvXQp*____________"
echo off "BB____B_________8______8amJvxrvvvvncZkad0LQZmqpppdddbbpwmO00mppqwwwwZOZQZkabLnnXcvvuxcCwa8___8________"
echo off "_____B________8________BWhZJcunnnnxn0bbm00O0LLqpqddddbkkkkkkbbbdpqwmZOQCJqhhQnnvunncULwaW_B___________"
echo off "___________________8___B8MomJYvxxnxz00LJCOwQLLL0OmwmwwmZmwwwmOOZZOQQLCJCQ0mw0XcvczXJ0poM8B____________"
echo off "____B_________B______8___8Mod0CCXXUJCJQmwddmQJUC0QZZOOZmmmmmmZO0QQLL00OZOQLJJJJJUCOwk*M8B_________BB_B"
echo off "_BB___8_________B____8__8_8W#adO00qpppdko#*kwO00CCQQ0ZwwZOOZO000LL00mqddppqwwmwwwpkoMW____________BB__"
echo off "__________________88____88__8WW#aoakh*##WWW#hbpqwmwdhoooooabdpmOO0Zqka****oooo**#MW&&8_B_B_____B____BB"
echo off "____________BBB_________88__B8&&MMWWWW&&88WWM*hkhhaooaaaahakhkpppbka#W&WWWWWWW&&&8________B_BB_______B"
echo off "____________B______________________8__8____8W#**oaakkhhhhhbbkhkbka*#W8_____8__________________________"
echo off "___B__B___________B_________________B_______8&WM#*aakbhhkkkkkhhhao#W&__88___B__________________BBB_BBB"
echo off "___B__BB______________B_BBB_______BB______B___8WM##ohhhhkbbhha***MW8_________________BBB_BB___BBBB_BBB"
echo off "BB_BBBBBB_______________________B_BB___________8&&#**ohaaahao##MW&___8______________________BBBB__BBBB"
echo off "BBBBBB_BBBBBBBBB____B_B______B___BB_______8______8&WM#*oo*#MWWW&8______B__________________BBB__BBB_BB_"
echo off "BBBBB_B__BBBB__B___________B_BB___________________888&&88888888___________________BB________BB_BBBBBB_"
pause
color 4c
echo "ONI{JJIRFH(U*(URFH*(WERF*EWRFWJER*&IWEUOJK(*""))))}MASSIVE SHIT"
pause